package com.example.tests.assertions.responses;

import com.example.responses.Addresses;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Addresses} specific assertions - Generated by CustomAssertionGenerator.
 */
public class AddressesAssert extends AbstractAssert<AddressesAssert, Addresses> {

  /**
   * Creates a new <code>{@link AddressesAssert}</code> to make assertions on actual Addresses.
   * @param actual the Addresses we want to make assertions on.
   */
  public AddressesAssert(Addresses actual) {
    super(actual, AddressesAssert.class);
  }

  /**
   * An entry point for AddressesAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAddresses)</code> and get specific assertion with code completion.
   * @param actual the Addresses we want to make assertions on.
   * @return a new <code>{@link AddressesAssert}</code>
   */
  public static AddressesAssert assertThat(Addresses actual) {
    return new AddressesAssert(actual);
  }

  /**
   * Verifies that the actual Addresses's href is equal to the given one.
   * @param href the given href to compare the actual Addresses's href to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Addresses's href is not equal to the given one.
   */
  public AddressesAssert hasHref(String href) {
    // check that actual Addresses we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting href of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualHref = actual.getHref();
    if (!Objects.areEqual(actualHref, href)) {
      failWithMessage(assertjErrorMessage, actual, href, actualHref);
    }

    // return the current assertion for method chaining
    return this;
  }

}
