package com.example.assertions.responses;

import com.example.responses.Self;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Self} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SelfAssert extends AbstractAssert<SelfAssert, Self> {

  /**
   * Creates a new <code>{@link SelfAssert}</code> to make assertions on actual Self.
   * @param actual the Self we want to make assertions on.
   */
  public SelfAssert(Self actual) {
    super(actual, SelfAssert.class);
  }

  /**
   * An entry point for SelfAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(mySelf)</code> and get specific assertion with code completion.
   * @param actual the Self we want to make assertions on.
   * @return a new <code>{@link SelfAssert}</code>
   */
  public static SelfAssert assertThat(Self actual) {
    return new SelfAssert(actual);
  }

  /**
   * Verifies that the actual Self's href is equal to the given one.
   * @param href the given href to compare the actual Self's href to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Self's href is not equal to the given one.
   */
  public SelfAssert hasHref(String href) {
    // check that actual Self we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting href of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualHref = actual.getHref();
    if (!Objects.areEqual(actualHref, href)) {
      failWithMessage(assertjErrorMessage, actual, href, actualHref);
    }

    // return the current assertion for method chaining
    return this;
  }

}
